---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-prober-config
  namespace: default
data:
  ONCALL_EXPORTER_API_URL: "http://oncall:8080/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-prober
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-prober
  template:
    metadata:
      labels:
        app: oncall-prober
    spec:
      containers:
        - name: oncall-prober
          image: oncall-prober:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ONCALL_EXPORTER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: oncall-prober-config
                  key: ONCALL_EXPORTER_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: oncall-prober
  namespace: default
  labels:
    app: oncall-prober
spec:
  selector:
    app: oncall-prober
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP